/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import model.Prodavac;
import model.Racun;
import model.StavkaRacuna;
import modeli.ModelTabeleRacuna;

/**
 *
 * @author Omnix
 */
public class PretraziRacuneForma extends javax.swing.JFrame {

    private List<Racun> listaRacuna = new ArrayList<>();
    private List<Racun> filterovaniRacuni = new ArrayList<>();

    /**
     * Creates new form PretraziRacuneForm
     */
    public PretraziRacuneForma() {
        initComponents();
        napuniCombobox();
        listaRacuna = Kontroler.getInstance().vratiSve(new Racun());
        osveziTabelu(listaRacuna);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRacuni = new javax.swing.JTable();
        cmbZaposleni = new javax.swing.JComboBox<>();
        btnFilterZaposleni = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        btnFilterMusterija = new javax.swing.JButton();
        btnPonisti = new javax.swing.JButton();
        btnDetaljnije = new javax.swing.JButton();
        btnFilterOBA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblRacuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRacuni);

        cmbZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbZaposleniActionPerformed(evt);
            }
        });

        btnFilterZaposleni.setText("Filtriraj po zaposlenom");
        btnFilterZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterZaposleniActionPerformed(evt);
            }
        });

        btnFilterMusterija.setText("Filtriraj po musteriji");
        btnFilterMusterija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterMusterijaActionPerformed(evt);
            }
        });

        btnPonisti.setText("Ponisti filter");
        btnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiActionPerformed(evt);
            }
        });

        btnDetaljnije.setText("Detaljnije");
        btnDetaljnije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljnijeActionPerformed(evt);
            }
        });

        btnFilterOBA.setText("Filtriraj po OBA");
        btnFilterOBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterOBAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbZaposleni, 0, 247, Short.MAX_VALUE)
                            .addComponent(txtUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFilterZaposleni)
                            .addComponent(btnFilterMusterija, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFilterOBA, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDetaljnije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPonisti, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFilterZaposleni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFilterMusterija)))
                    .addComponent(btnFilterOBA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnPonisti, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetaljnije, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbZaposleniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbZaposleniActionPerformed

    private void btnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiActionPerformed
        osveziTabelu(listaRacuna);
    }//GEN-LAST:event_btnPonistiActionPerformed

    private void btnFilterZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterZaposleniActionPerformed
        Prodavac p = (Prodavac) cmbZaposleni.getSelectedItem();
        filterovaniRacuni = new ArrayList<>();

        for (Racun r : listaRacuna) {
            if (r.getProdavac().equals(p)) {
                filterovaniRacuni.add(r);
            }
        }
        osveziTabelu(filterovaniRacuni);
    }//GEN-LAST:event_btnFilterZaposleniActionPerformed

    private void btnFilterMusterijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterMusterijaActionPerformed
        String username = txtUsername.getText().trim();

        if (username.isEmpty()) {
            osveziTabelu(listaRacuna);
            return;
        }

        filterovaniRacuni = new ArrayList<>();
        for (Racun r : listaRacuna) {
            if (r.getMusterija().getUsername().equals(username)) {
                filterovaniRacuni.add(r);
            }
        }
        osveziTabelu(filterovaniRacuni);
    }//GEN-LAST:event_btnFilterMusterijaActionPerformed

    private void btnFilterOBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterOBAActionPerformed
        Prodavac p = (Prodavac) cmbZaposleni.getSelectedItem();
        String username = txtUsername.getText().trim();
        filterovaniRacuni = new ArrayList<>();

        for (Racun r : listaRacuna) {
            if (r.getProdavac().equals(p)) {
                filterovaniRacuni.add(r);
            }
        }

        if (username.isEmpty()) {
            osveziTabelu(filterovaniRacuni);
            return;
        }

        for (Racun r : listaRacuna) {
            if (!r.getMusterija().getUsername().equals(username)) {
                filterovaniRacuni.remove(r);
            }
        }

        osveziTabelu(filterovaniRacuni);
    }//GEN-LAST:event_btnFilterOBAActionPerformed

    private void btnDetaljnijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljnijeActionPerformed
        int selektovaniRed = tblRacuni.getSelectedRow();
        
        if (selektovaniRed == -1){
            JOptionPane.showMessageDialog(this, "Izaberite neki racun.", "Racun nije odabran", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        ModelTabeleRacuna modelTabele = (ModelTabeleRacuna) tblRacuni.getModel();
        List<Racun> tempLista = modelTabele.getListaRacuna();
        
        Racun r = tempLista.get(selektovaniRed);
        StavkaRacuna placeholderStavka = new StavkaRacuna();
        placeholderStavka.setRacun(r);
        List<StavkaRacuna> listaStavki = Kontroler.getInstance().vratiSve(placeholderStavka);
        
        RacunDetaljnijeForma rdf = new RacunDetaljnijeForma(this, true, r, listaStavki);
        rdf.setVisible(true);
    }//GEN-LAST:event_btnDetaljnijeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretraziRacuneForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretraziRacuneForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretraziRacuneForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretraziRacuneForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PretraziRacuneForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetaljnije;
    private javax.swing.JButton btnFilterMusterija;
    private javax.swing.JButton btnFilterOBA;
    private javax.swing.JButton btnFilterZaposleni;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JComboBox<Prodavac> cmbZaposleni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRacuni;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void napuniCombobox() {
        List<Prodavac> listaProdavaca = Kontroler.getInstance().vratiSve(new Prodavac());

        for (Prodavac p : listaProdavaca) {
            cmbZaposleni.addItem(p);
        }
    }

    private void osveziTabelu(List<Racun> listaRacuna) {
        ModelTabeleRacuna mtr = new ModelTabeleRacuna(listaRacuna);
        tblRacuni.setModel(mtr);
    }
}
