/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import kontroler.Kontroler;
import model.Prodavac;
import modeli.ModelTabeleMusterija;
import server.PokreniServer;

/**
 *
 * @author Omnix
 */
public class ServerForma extends javax.swing.JFrame {

    private PokreniServer ps;
    private PostaviAngazovanjeForma paf;

    /**
     * Creates new form ServerForma
     */
    public ServerForma() {
        initComponents();
    }

    public ServerForma(Prodavac p) {
        initComponents();
        Kontroler.getInstance().setSf(this);
        setTitle("Zdravo " + p.getIme() + "!");
        ps = new PokreniServer();
        ps.start();
        paf = new PostaviAngazovanjeForma(this, true, p, null, null);
        paf.setVisible(true);

        osveziTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOnlineMusterije = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemAngazovanja = new javax.swing.JMenuItem();
        menuItemKategorijeMusterija = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblOnlineMusterije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOnlineMusterije);

        menuFile.setText("File");

        menuItemAngazovanja.setText("Angazovanja");
        menuItemAngazovanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAngazovanjaActionPerformed(evt);
            }
        });
        menuFile.add(menuItemAngazovanja);

        menuItemKategorijeMusterija.setText("Kategorije musterija");
        menuItemKategorijeMusterija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKategorijeMusterijaActionPerformed(evt);
            }
        });
        menuFile.add(menuItemKategorijeMusterija);

        jMenuBar1.add(menuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(kontroler.Kontroler.getInstance().getListaNiti());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuItemAngazovanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAngazovanjaActionPerformed
        AngazovanjaForma af = new AngazovanjaForma(this, false);
        af.setVisible(true);
    }//GEN-LAST:event_menuItemAngazovanjaActionPerformed

    private void menuItemKategorijeMusterijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKategorijeMusterijaActionPerformed
        KategorijeMusterijaForma kmf = new KategorijeMusterijaForma(this, false);
        kmf.setVisible(true);
    }//GEN-LAST:event_menuItemKategorijeMusterijaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemAngazovanja;
    private javax.swing.JMenuItem menuItemKategorijeMusterija;
    private javax.swing.JTable tblOnlineMusterije;
    // End of variables declaration//GEN-END:variables

    public void osveziTabelu() {
        ModelTabeleMusterija mtm = new ModelTabeleMusterija(Kontroler.getInstance().vratiListuOnlineMusterija());
        tblOnlineMusterije.setModel(mtm);
    }
}
