/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.angazovanje;

import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import model.Angazovanje;
import model.Prodavac;
import model.Smene;
import model.TerminDezurstva;

/**
 *
 * @author Omnix
 */
public class PostaviAngazovanjeForma extends javax.swing.JDialog {

    Prodavac p;
    TerminDezurstva t;
    Angazovanje a;
    AngazovanjaForma af;

    /**
     * Creates new form PostaviAngazovanjeForma
     */
    public PostaviAngazovanjeForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public PostaviAngazovanjeForma(java.awt.Frame parent, boolean modal, Prodavac p, Angazovanje a, AngazovanjaForma af) {
        super(parent, modal);
        initComponents();
        this.p = p;
        txtProdavac.setText(p.toString());

        if (a == null) {
            btnIzmeni.setVisible(false);
            btnOdustani.setVisible(false);
            btnPostavi.setVisible(true);
        } else {
            this.af = af;
            this.a = a;
            this.t = a.getTermin();
            btnIzmeni.setVisible(true);
            btnOdustani.setVisible(true);
            btnPostavi.setVisible(false);
            cmbSmene.setSelectedItem(t.getSmena());
        }

        // Listener za promenu smene
        cmbSmene.addActionListener(e -> {
            Smene selektovana = (Smene) cmbSmene.getSelectedItem();
            if (selektovana != null) {
                txtVremeOd.setText(selektovana.getVremeOd().toString());
                txtVremeDo.setText(selektovana.getVremeDo().toString());
            }
        });

        // inicijalno postavljanje vremena
        Smene prva = (Smene) cmbSmene.getSelectedItem();
        if (prva != null) {
            txtVremeOd.setText(prva.getVremeOd().toString());
            txtVremeDo.setText(prva.getVremeDo().toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProdavac = new javax.swing.JTextField();
        txtVremeOd = new javax.swing.JTextField();
        txtVremeDo = new javax.swing.JTextField();
        cmbSmene = new javax.swing.JComboBox<>();
        btnPostavi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Postavi angazovanje");
        setAlwaysOnTop(true);

        jLabel1.setText("Ime i prezime");

        jLabel2.setText("Smena");

        jLabel3.setText("Vreme pocetka smene");

        jLabel4.setText("Vreme kraja smene");

        txtProdavac.setEditable(false);

        txtVremeOd.setEditable(false);

        txtVremeDo.setEditable(false);

        cmbSmene.setModel(new DefaultComboBoxModel(Smene.values()));

        btnPostavi.setText("Postavi");
        btnPostavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostaviActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPostavi, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProdavac)
                            .addComponent(txtVremeOd, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtVremeDo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(cmbSmene, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProdavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbSmene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVremeOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVremeDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPostavi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPostaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostaviActionPerformed

        TerminDezurstva td = new TerminDezurstva();
        LocalTime vremeOd = LocalTime.parse(txtVremeOd.getText());
        LocalTime vremeDo = LocalTime.parse(txtVremeDo.getText());

        switch ((Smene) cmbSmene.getSelectedItem()) {
            case Smene.PRVA:
                td.setId(1);
                break;
            case Smene.DRUGA:
                td.setId(2);
                break;
            case Smene.TRECA:
                td.setId(3);
                break;
            default:
                throw new AssertionError();
        }

        td.setSmena((Smene) cmbSmene.getSelectedItem());
        td.setVremeOd(vremeOd);
        td.setVremeDo(vremeDo);

        Angazovanje a = new Angazovanje(p, td, LocalDate.now());
        Kontroler.getInstance().getSf().setA(a);
        boolean angazovanjePostavljeno = Kontroler.getInstance().dodaj(a);

        if (angazovanjePostavljeno) {
            JOptionPane.showMessageDialog(this, "Sistem je uspesno zapoceo termin dezurstva.", "Smena zapoceta", JOptionPane.INFORMATION_MESSAGE);
            Kontroler.getInstance().getSf().setA(a);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Ovaj termin dezurstva je vec zapocet, sistem vas preusmerava na glavnu formu.", "Smena vec postoji", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }

    }//GEN-LAST:event_btnPostaviActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        TerminDezurstva td = new TerminDezurstva();
        LocalTime vremeOd = LocalTime.parse(txtVremeOd.getText());
        LocalTime vremeDo = LocalTime.parse(txtVremeDo.getText());

        switch ((Smene) cmbSmene.getSelectedItem()) {
            case Smene.PRVA:
                td.setId(1);
                break;
            case Smene.DRUGA:
                td.setId(2);
                break;
            case Smene.TRECA:
                td.setId(3);
                break;
            default:
                throw new AssertionError();
        }

        td.setSmena((Smene) cmbSmene.getSelectedItem());
        td.setVremeOd(vremeOd);
        td.setVremeDo(vremeDo);

        a.setTermin(td);
        boolean angazovanjePromenjeno = Kontroler.getInstance().izmeni(a);

        if (angazovanjePromenjeno) {
            JOptionPane.showMessageDialog(this, "Uspesno ste promenili angazovanje.", "Smena izmenjena", JOptionPane.INFORMATION_MESSAGE);
            af.osveziTabelu();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Postoji problem sa izmenom angazovanja.", "Smena NIJE izmenjena", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostaviAngazovanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostaviAngazovanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostaviAngazovanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostaviAngazovanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PostaviAngazovanjeForma dialog = new PostaviAngazovanjeForma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnPostavi;
    private javax.swing.JComboBox<String> cmbSmene;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtProdavac;
    private javax.swing.JTextField txtVremeDo;
    private javax.swing.JTextField txtVremeOd;
    // End of variables declaration//GEN-END:variables
}
