/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Frame;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import kontroler.Kontroler;
import model.Musterija;
import operacije.Operacija;
import transfer.KlijentskiZahtev;

/**
 *
 * @author Omnix
 */
public class IzmenaKlijentaForma extends javax.swing.JDialog {

    private Musterija m;
    private Musterija izmenjen;
    private boolean azuriranjeSifre;

    /**
     * Creates new form IzmenaKlijentaForm
     */
    public IzmenaKlijentaForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public IzmenaKlijentaForma(java.awt.Frame parent, boolean modal, Musterija m, boolean azuriranjeSifre) {
        super(parent, modal);
        initComponents();
        this.m = m;
        this.azuriranjeSifre = azuriranjeSifre;

        txtEmail.setText(m.getEmail());
        txtKategorija.setText(m.getKategorijaMusterije().toString());
        txtUsername.setText(m.getUsername());

        txtNoviPassword.setEnabled(azuriranjeSifre);
        txtUsername.setEnabled(!azuriranjeSifre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtKategorija = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtNoviPassword = new javax.swing.JTextField();
        txtStariPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Email");

        jLabel2.setText("Kategorija");

        jLabel3.setText("Username");

        jLabel4.setText("Stari password");

        jLabel5.setText("Novi password");

        txtEmail.setEditable(false);
        txtEmail.setEnabled(false);

        txtKategorija.setEditable(false);
        txtKategorija.setEnabled(false);

        jButton1.setText("Izmeni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmail)
                    .addComponent(txtKategorija)
                    .addComponent(txtUsername)
                    .addComponent(txtNoviPassword)
                    .addComponent(txtStariPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNoviPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStariPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        KlijentskiZahtev kz = new KlijentskiZahtev();
        

        if (!txtStariPassword.getText().equals(m.getPassword())) {
            JOptionPane.showMessageDialog(this, "Stari password nije ispravan.");
            return;
        }

        Musterija izmenjen = new Musterija();
        this.izmenjen = izmenjen;
        izmenjen.setId(m.getId());
        izmenjen.setEmail(m.getEmail());
        izmenjen.setKategorijaMusterije(m.getKategorijaMusterije());
        izmenjen.setPreostaloVreme(m.getPreostaloVreme());

        if (azuriranjeSifre) {
            String password = txtNoviPassword.getText();

            if (!password.equals(m.getPassword())) {
                if (password == null || password.length() <= 5) {
                    JOptionPane.showMessageDialog(this, "Password koji ste uneli nije validnog formata. [mora biti duzi od 5 karaktera]");
                    return;
                }
                izmenjen.setUsername(m.getUsername());
                izmenjen.setPassword(password);

                kz.setOperacija(Operacija.AZURIRANJE_PASSWORD);
                kz.setParam(izmenjen);

            } else {
                JOptionPane.showMessageDialog(this, "Niste promenili password.");
                return;
            }

            izmenjen.setPassword(password);
        } else {
            String username = txtUsername.getText().trim();

            if (!username.equals(m.getUsername())) {
                if (username == null || username.length() < 3) {
                    JOptionPane.showMessageDialog(this, "Username koji ste uneli nije validnog formata.");
                    return;
                }
                izmenjen.setPassword(m.getPassword());
                izmenjen.setUsername(username);

                kz.setOperacija(Operacija.AZURIRANJE_USERNAME);
                kz.setParam(izmenjen);

            } else {
                JOptionPane.showMessageDialog(this, "Niste promenili username.");
                return;
            }
        }

        try {
            Komunikacija.getInstance().posaljiZahtev(kz);
        } catch (IOException ex) {
            Logger.getLogger(IzmenaKlijentaForma.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzmenaKlijentaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzmenaKlijentaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzmenaKlijentaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzmenaKlijentaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IzmenaKlijentaForma dialog = new IzmenaKlijentaForma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKategorija;
    private javax.swing.JTextField txtNoviPassword;
    private javax.swing.JTextField txtStariPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    public void obradiPromenu(boolean izmenjeno) {
        if (azuriranjeSifre) {
            if (izmenjeno) {
                Kontroler.getInstance().getKf().setM(izmenjen);
                JOptionPane.showMessageDialog(this, "Uspesno ste promenili lozinku!");
            } else {
                JOptionPane.showMessageDialog(this, "Lozinka nije promenjena, problem sa serverom.");
                return;
            }
        } else {
            if (izmenjeno) {
                Kontroler.getInstance().getKf().setM(izmenjen);
                JOptionPane.showMessageDialog(this, "Uspesno ste promenili username!");
            } else {
                JOptionPane.showMessageDialog(this, "Username nije promenjen, zauzet je ili postoji problem sa serverom.!");
                return;
            }
        }
        this.m = Kontroler.getInstance().getKf().getM();
        Kontroler.getInstance().getKf().osveziTitle();
    }
}
