/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.Musterija;
import niti.MusterijaTimerNit;
import operacije.Operacija;
import transfer.KlijentskiZahtev;

/**
 *
 * @author Omnix
 */
public class KlijentskaForma extends javax.swing.JFrame {

    private Musterija m;
    private MusterijaTimerNit mtn;
    private IzmenaKlijentaForma ikf;

    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
    }

    public KlijentskaForma(Musterija m) {
        try {
            this.m = m;
            initComponents();
            osveziTitle();
            kontroler.Kontroler.getInstance().setKf(this);
            Komunikacija.getInstance().start();
            mtn = new MusterijaTimerNit(this, m, lblVreme);
            mtn.start();

            setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

            addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    KlijentskiZahtev kz = new KlijentskiZahtev(m, Operacija.LOGOUT);
                    try {
                        Komunikacija.getInstance().posaljiZahtev(kz);
                    } catch (IOException ex) {
                        Logger.getLogger(KlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    mtn.setKraj(true);
                    dispose(); // zatvara prozor
                }
            });
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Nije uspostavljena konekcija sa serverom.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnIzmeniUsername = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblVreme = new javax.swing.JLabel();
        btnIzmeniPassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnIzmeniUsername.setText("Izmeni username");
        btnIzmeniUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniUsernameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Preostalo vreme na nalogu: ");

        lblVreme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVreme.setText("VREME");

        btnIzmeniPassword.setText("Izmeni password");
        btnIzmeniPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIzmeniUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzmeniPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVreme)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblVreme))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(btnIzmeniUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzmeniPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        KlijentskiZahtev kz = new KlijentskiZahtev(m, Operacija.LOGOUT);
        try {
            Komunikacija.getInstance().posaljiZahtev(kz);
        } catch (IOException ex) {
            Logger.getLogger(KlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        mtn.setKraj(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnIzmeniUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniUsernameActionPerformed
        IzmenaKlijentaForma ikf = new IzmenaKlijentaForma(this, true, m, false);
        this.ikf = ikf;
        ikf.setVisible(true);
    }//GEN-LAST:event_btnIzmeniUsernameActionPerformed

    private void btnIzmeniPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPasswordActionPerformed
        IzmenaKlijentaForma ikf = new IzmenaKlijentaForma(this, true, m, true);
        this.ikf = ikf;
        ikf.setVisible(true);
    }//GEN-LAST:event_btnIzmeniPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniPassword;
    private javax.swing.JButton btnIzmeniUsername;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblVreme;
    // End of variables declaration//GEN-END:variables

    public void prikaziLogoutPoruku(boolean serverLogout) {
        if (serverLogout) {
            mtn.setKraj(true);
            JOptionPane.showMessageDialog(this, "Administrator vas je izbacio.", "Odlogovani ste", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Uspesno ste se izlogovali.", "Logout uspesan", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }

    }

    public void istekloVreme() {
        try {
            Komunikacija.getInstance().setKraj(true);
        } catch (IOException ex) {
            Logger.getLogger(KlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Nestalo vam je vremena, uplatite jos kod prodavca kako biste koristili nalog.", "Logout izvrsen", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }

    public IzmenaKlijentaForma getIkf() {
        return ikf;
    }

    public void setIkf(IzmenaKlijentaForma ikf) {
        this.ikf = ikf;
    }

    public Musterija getM() {
        return m;
    }

    public void setM(Musterija m) {
        this.m = m;
    }

    void osveziTitle() {
        setTitle("Dobrodosli " + m.getUsername());
    }

}
